### ISSUE TITLE
GIT_HTTP_BACKEND_SOURCES should be overwritable

### ISSUE THREAD

**Issue by windtail** [drmikehenry/romt#11]
i am trying to make a romt docker container base on alpine3.14, the `git-http-backend` is at `/usr/libexec/git-core/git-http-backend` instead of 
`/usr/lib/git-core/git-http-backend`.

maybe we could add another argument `--git-http-backend` or lookup it in PATH environment

**Comment by drmikehenry** [comment]
The location of `git-http-backend` may be manually configured as explained in <https://github.com/drmikehenry/romt/blob/main/README.rst#serve-operation>; these instructions have been pasted below for the non-Windows case, and have been edited for Alpine's path:

> To manually setup the Git backend, create a script file in `cgi-bin/`
> with contents similar to these examples (depending on platform):
> 
> ...
>
> -   On non-Windows, create `cgi-bin/git-http-backend.sh` with contents:
> 
>         #!/bin/sh
>         exec '/usr/libexec/git-core/git-http-backend'
> 
>     Then make the script executable:
> 
>     ``` sh
>     chmod +x cgi-bin/git-http-backend.sh
>     ```

Before running `romt serve`, pre-create the script `cgi-bin/git-http-backend.sh` as shown above.  Thereafter, `romt serve` will use `cgi-bin/git-http-backend.sh` to invoke the actual backend.

Alternatively, instead of making the script `git-http-backend.sh`, you may create a symlink before running `romt serve`:

```sh
mkdir cgi-bin
ln -s /usr/libexec/git-core/git-http-backend cgi-bin/git-http-backend
```

**Comment by windtail** [comment]
I apologize for my carelessness!

But I am a little surprised, usually a program is expected being configured by arguments, environment variables or config files.

**Comment by drmikehenry** [comment]
For `romt serve`, the design of Python's `http.server.CGIHTTPRequestHandler`
(which provides the underlying web server functionality) drove the method of
configuration.  This module expects CGI scripts to reside in a `cgi-bin/`
directory.  Whether the scripts are copies of the actual executable, links to
the executable, or separate shell scripts, they must be placed into `cgi-bin/`
somehow.  Once `cgi-bin/` is created with the proper contents, no additional
configuration is required for `romt serve`.  If `romt` were to use command-line
switches, environment variables, or a separate configuration file to specify the
location of `git-http-backend`, it would need to use this information to create
a CGI script in `cgi-bin/`, after which the configuration information would
become unnecessary.  In effect, `cgi-bin/git-http-backend.sh` serves as a
configuration file, with the additional ability to set environment variables or
perform other adjustments before invoking the actual Git backend.
